### ISSUE TITLE
Memory error with the last netdisco version

### ISSUE THREAD

**Issue by earendilfr** [netdisco/netdisco#1057]
## Current Behavior
Since I have upgraded with the last version of netdisco, I have weird issue (Out of memory) wit the pooler.
And it seems that part of the MIB are not loaded correctly...

Messages in logs:
```
Unlinked OID in CISCO-ENTITY-VENDORTYPE-OID-MIB: cevOtherCscLink ::= { cevOther 8 }
Undefined identifier: cevOther near line 129 of /opt/netdisco/netdisco-mibs/cisco/CISCO-ENTITY-VENDORTYPE-OID-MIB.my
Unlinked OID in CISCO-ENTITY-VENDORTYPE-OID-MIB: cevOtherSce8000Sip ::= { cevOther 6 }
Undefined identifier: cevOther near line 128 of /opt/netdisco/netdisco-mibs/cisco/CISCO-ENTITY-VENDORTYPE-OID-MIB.my
Unlinked OID in CISCO-ENTITY-VENDORTYPE-OID-MIB: cevOtherSce8000Scm ::= { cevOther 5 }
Undefined identifier: cevOther near line 127 of /opt/netdisco/netdisco-mibs/cisco/CISCO-ENTITY-VENDORTYPE-OID-MIB.my
Unlinked OID in CISCO-ENTITY-VENDORTYPE-OID-MIB: cevNmeApaLink ::= { cevOther 3 }
Undefined identifier: cevOther near line 126 of /opt/netdisco/netdisco-mibs/cisco/CISCO-ENTITY-VENDORTYPE-OID-MIB.my
Unlinked OID in CISCO-ENTITY-VENDORTYPE-OID-MIB: cevOtherMoH ::= { cevOther 2 }
Undefined identifier: cevOther near line 125 of /opt/netdisco/netdisco-mibs/cisco/CISCO-ENTITY-VENDORTYPE-OID-MIB.my
Unlinked OID in CISCO-ENTITY-VENDORTYPE-OID-MIB: cevOtherUnknownCard ::= { cevOther 1 }
Undefined identifier: cevOther near line 124 of /opt/netdisco/netdisco-mibs/cisco/CISCO-ENTITY-VENDORTYPE-OID-MIB.my
Out of memory!
MCE worker 20874.0 exited prematurely.
Out of memory!
MCE worker 20890.0 exited prematurely.
Out of memory!
Out of memory!
MCE worker 20868.0 exited prematurely.
Out of memory!
MCE worker 20880.0 exited prematurely.
Out of memory!
Out of memory!
Out of memory!
MCE worker 20886.0 exited prematurely.
MCE worker 20892.0 exited prematurely.
Out of memory!
MCE worker 20894.0 exited prematurely.
Out of memory!
MCE worker 20889.0 exited prematurely.
Out of memory!
MCE worker 20877.0 exited prematurely.
Out of memory!
MCE worker 20891.0 exited prematurely.
Out of memory!
MCE worker 20893.0 exited prematurely.
Out of memory!
Out of memory!
MCE worker 20884.0 exited prematurely.
Out of memory!
MCE worker 20565.0 exited prematurely.
Out of memory!
MCE worker 20869.0 exited prematurely.
Out of memory!
MCE worker 20613.0 exited prematurely.
Out of memory!
MCE worker 20888.0 exited prematurely.
error running job: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  out of memory
DETAIL:  Failed on request of size 16. [for Statement "SELECT me.ip, me.creation, me.dns, me.description, me.uptime, me.contact, me.name, me.location, me.layers, me.num_ports, me.mac, me.serial, me.chassis_id, me.model, me.ps1_type, me.ps2_type, me.ps1_status, me.ps2_status, me.fan, me.slots, me.vendor, me.os, me.os_ver, me.log, me.snmp_ver, me.snmp_comm, me.snmp_class, me.snmp_engineid, me.vtp_domain, me.last_discover, me.last_macsuck, me.last_arpnip, me.is_pseudo, me.pae_is_enabled, me.custom_fields, to_char(me.creation, 'YYYY-MM-DD HH24:MI'), to_char(me.last_arpnip,   'YYYY-MM-DD HH24:MI'), to_char(me.last_discover, 'YYYY-MM-DD HH24:MI'), to_char(me.last_macsuck,  'YYYY-MM-DD HH24:MI'), extract(epoch from (age(LOCALTIMESTAMP, me.creation))), extract(epoch from (age(LOCALTIMESTAMP, me.last_arpnip))), extract(epoch from (age(LOCALTIMESTAMP, me.last_discover))), extract(epoch from (age(LOCALTIMESTAMP, me.last_macsuck))), replace(age(timestamp 'epoch' + me.uptime / 100 * interval '1 second', timestamp '1970-01-01 00:00:00-00')::text, 'mon', 'month') FROM device me WHERE ( me.ip = ? )" with ParamValues: 1='10.10.36.10'] at /opt/netdisco/perl5/lib/perl5/App/Netdisco/Util/Device.pm line 65
```

But memory seems OK:
```top
top - 16:46:52 up 28 min,  1 user,  load average: 0.15, 1.94, 3.70
Tasks: 619 total,   1 running, 608 sleeping,   0 stopped,  10 zombie
%Cpu(s):  0.0 us,  0.1 sy,  0.0 ni, 99.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  23794.5 total,  11301.3 free,   9510.9 used,   2982.3 buff/cache
MiB Swap:   2048.0 total,   2048.0 free,      0.0 used.  13512.1 avail Mem
```

## Steps to Reproduce (for bugs)

1. Start netdisco-backend service
2. Wait few minutes
3. check the backend logs

## Context
The issue seems have appear with the last version

## Your Environment

* Netdisco version used: 2.63.1
* SNMP::Info version used: 3.92

## Config info (deployment.yml)
```yaml
#
# NETDISCO 2 CONFIGURATION FILE
#
# Settings in this file override share/config.yml
# See App::Netdisco::Manual::Configuration for more info.

# ------------------
# ESSENTIAL SETTINGS
# ------------------

database:
  name: 'netdiscodb'
  user: 'netdisco'
  pass: 'xxxxxxxx'

# -----------------
# LOG SETTINGS
# -----------------
log: 'warning'
log_format: '[%T] {PID: %P} {Level:%L} %m'

# set to false if you MUST maintain backwards compatibility
# with Netdisco 1.x web frontend.
# `````````````````````````````````````````````````````````
safe_password_store: true

# SNMP community string(s)
# ````````````````````````
device_auth:
  - tag: 'xxxxxx'
    user: 'xxxxxx'
    auth:
      proto: 'SHA'
      pass: 'xxxxxx'
    priv:
      proto: 'AES'
      pass: 'xxxxxx'
  - tag: 'xxxxxx'
    user: 'xxxxxx'
    auth:
      proto: 'SHA'
      pass: 'xxxxxx'
    priv:
      proto: 'AES'
      pass: 'xxxxxx'
  - tag: 'xxxxxx'
    user: 'xxxxxx'
    auth:
      proto: 'MD5'
      pass: 'xxxxxx'
    priv:
      proto: 'AES'
      pass: 'xxxxxx'
  - tag: 'xxxxxx'
    community: 'xxxxxx'
    read: true
    write: false
  - tag: 'xxxxxx'
    community: 'xxxxxx'
    read: true
    write: false
  - tag: 'xxxxxx'
    community: 'xxxxxx'
    read: true
    write: false
  - tag: 'sshbigip'
    driver: cli
    platform: BigIP
    only:
      - 10.x.y.z
      - 10.x.y.z
      - 10.x.y.z
      - 10.x.y.z
    username: xxxxxx
    ssh_master_opts:
      - "-i"
      - "~/.ssh/rancid_ed25519"


# this is the schedule for automatically keeping netdisco up-to-date
# ``````````````````````````````````````````````````````````````````
schedule:
  discoverall:
    when: '* */6 * * *'
  macwalk:
    when:
      min: '*/20'
  arpwalk:
    when:
      min: '15,45'
  nbtwalk: null
  expire:
    when: '20 23 * * *'
  makerancidconf:
    when: '30 */6 * * *'
  makeansiblehost:
    when: '30 */6 * * *'

# do not discover IP Phones or Wireless Access Points.
# usually these are visible as device neighbors but don't support
# SNMP, which just clogs up the job queue.
# ```````````````````````````````````````````````````````````````
#discover_no_type:
#  - '(?i)phone'
#  - '(?i)cisco\s+AIR-(L|C)AP'
discover_waps: false
discover_phones: false

# number of SNMP workers to run in parallel (in netdisco-backend).
# the default is twice the number of CPU cores. increase this if
# your system has few cores and the schedule is taking too long.
# ```````````````````````````````````````````````````````````````
workers:
  tasks: 'AUTO * 8'
  timeout: 600
  sleep_time: 1
  min_runtime: 0
  max_deferrals: 10
  retry_after: '1 day'

# number of parallel DNS queries for node names
# `````````````````````````````````````````````
dns:
  max_outstanding: 50

# Domain suffix to remove
# `````````````````````````````````````````````
domain_suffix:
  - '.xxxxxx'
  - '.yyyyyy'

# We disable completely the Netbios discover
# `````````````````````````````````````````````````````````````````````
nbtstat_no:
  - 'any'

# Global tuning for MAC suck to take in count users in VLAN
# WARNING: on Cisco switch, you should allow polling on SNMP context for each VLAN
# `````````````````````````````````````````````````````````````````````
macsuck_all_vlans: true

# We clear job that didn't have run after 2 days
# `````````````````````````````````````````````````````````````````````
expire_jobs: 2

# Turn this on to have Netdisco do a reverse lookup of the device sysName.0 field 
# to use as the management IP address for a device.
# `````````````````````````````````````````````````````````````````````
reverse_sysname: true

# Web tune parameters
# `````````````````````````````````````````````````````````````````````
table_pagesize: 50


# Custom reports
# `````````````````````````````````````````````````````````````````````
reports:
  - tag: ap_cdp_neighbors
    label: 'Access Point Neighbors'
    category: 'Wireless'
    columns:
      - { switch: 'Switch Name' }
      - { switch_port: 'Switch port' }
      - { controller: 'Controller' }
      - { ap_name: 'AP Name' }
    query: |
      SELECT DISTINCT
        sw.name AS switch,
        sw_port.port AS switch_port,
        ctrl.name AS controller,
        ctrl_port.name AS ap_name
      FROM device AS sw
        INNER JOIN device_port AS sw_port ON sw_port.ip = sw.ip
        INNER JOIN device_port_properties AS sw_port_properties ON (sw_port.ip = sw_port_properties.ip and sw_port.port = sw_port_properties.port)
        INNER JOIN device_port AS ctrl_port ON (ctrl_port.mac::TEXT = sw_port.remote_id)
        INNER JOIN device AS ctrl ON (ctrl_port.ip = ctrl.ip)
      WHERE sw_port_properties.remote_is_wap = TRUE AND sw_port.remote_type LIKE 'Aruba%' AND
        sw.name ~* ? AND ctrl.name ~* ? AND ctrl_port.name ~* ? 
      ORDER BY ctrl_port.name;
    bind_params: ['switch', 'controller', 'ap_name']
    show_sidebar: true
  - tag: 'ap_inventory'
    label: 'Wifi Light AP Inventory'
    category: 'Device'
    columns:
      - { name: 'AP Name' }
      - { location: 'Location' }
      - { serial: 'Serial Number' }
      - { model: 'AP Model' }
      - { fw_ver: 'HW version' }
      - { sw_ver: 'SW version' }
      - { controllers: 'List of controllers' }
    query: |
      SELECT DISTINCT
        r[2] AS name, 
        r[3] as location, 
        serial, 
        model,
        array_to_string(array_remove(array_agg(DISTINCT fw_ver),''::text), ' | ') as fw_ver,
        array_to_string(array_remove(array_agg(DISTINCT sw_ver),''::text), ' | ') as sw_ver,
        array_to_string(array_remove(array_agg(DISTINCT controller),''::text), ' | ') as controllers
      FROM (
        SELECT 
          regexp_split_to_array(ctrl_module.description,E'\\s+\(\)') as r, 
          fw_ver, 
          sw_ver, 
          ctrl_module.serial as serial, 
          ctrl_module.model as model, 
          ctrl.name as controller
        FROM device_module AS ctrl_module
          INNER JOIN device AS ctrl ON ctrl_module.ip = ctrl.ip
        WHERE
          ctrl_module.type LIKE 'ap%' AND
          ctrl_module.serial ~* ? AND ctrl_module.model ~* ? AND ctrl.name ~* ?
      ) AS seq
      GROUP BY name, location, serial, model
      ORDER BY name;
    bind_params: ['serial', 'model', 'controller']
    show_sidebar: true
  - tag: 'hw_inventory'
    label: 'HW Devices Inventory'
    category: 'Device'
    columns:
      - {hostname: 'Name'}
      - {description: 'Description'}
      - {fw_ver: 'HW version'}
      - {serial: 'Serial'}
      - {model: 'Model'}
    query: |
      SELECT
        hostname,
        description,
        fw_ver,
        serial,
        model
      FROM(
        SELECT 
          substring(device.name, '^([^\.]+)') AS hostname,
          device_module.description AS description,
          CASE WHEN COALESCE(device_module.sw_ver,'') ~ '^[[:space:]]*$' 
            THEN device.os_ver
            ELSE device_module.sw_ver
          END AS fw_ver,
          device_module.serial AS serial,
          device_module.model AS model
        FROM device_module
          INNER JOIN device ON device.ip = device_module.ip
        WHERE device_module.class = 'chassis' AND device_module.serial <> '') AS seq
      WHERE
          hostname ~* ? AND model ~*  ? AND fw_ver ~* ?
      ORDER BY hostname;
    bind_params: ['hostname', 'model', 'os']
    show_sidebar: true
  - tag: 'device_poller_outofdate'
    label: 'Device Poller Out of Date'
    columns:
      - {name: 'Name'}
      - {ip: 'IP'}
      - {last_discover: 'Last Discovery Date'}
      - {last_macsuck: 'Last MAC discover Date'}
      - {last_arpnip: 'Last ARP discover Date'}
    query: |
      SELECT
        name,
        ip,
        last_discover, 
        last_macsuck, 
        last_arpnip
      FROM device
      WHERE
        age(now(),last_discover) > '2 days' OR age(now(),last_macsuck) > '2 days' OR age(now(),last_arpnip) > '2 days'
      ORDER BY name;

# LDAP authentication
# `````````````````````````````````````````````````````````````````````
ldap:
  servers:
    - 'xxxxxx'
    - 'yyyyyy'
  user_string: '%USER%@xxxxxx'
  opts:
    debug: 0

# Rancid configuration
# `````````````````````````````````````````````````````````````````````
rancid:
  rancid_conf: '/opt/rancid/etc'
  rancid_cvsroot: '/opt/rancid/var'
  down_age: '5 days'
  delimiter: ';'
  groups:
    my_compagny: [ 'any' ]
  default_group: 'my_compagny'
  by_hostname: [ 'group:my_compagny' ]
  excluded: [ 'group:rancid_exclude' ]
  vendormap:
    'cisco-nx':
      - 'os:nx-os'
    'fortigate':
      - 'vendor:fortinet'
    'bigip':
      - 'vendor:f5'

# Ansible configuration
# `````````````````````````````````````````````````````````````````````
extra_worker_plugins:
  - X::MakeAnsibleHosts
ansible:
  root_dir: '/opt/netdisco/network-ansible'
  down_age: '5 days'
  excluded: [ 'group:ansible_exclude' ]
  by_hostname: [ 'group:__ANY__' ]
  groups:
    'dc-mgmt':
      - 'group:dc_mgmt'
  osmap:
    'nxos':
      - 'os:nx-os'

# Web plugins
# `````````````````````````````````````````````````````````````````````
extra_web_plugins:
  - X::RANCID

plugin_rancid:
  location: "https://rancid.example.com/?p=%GROUP%;a=blob;f=configs/%DEVICE%;hb=HEAD"

# Custom groups / ACL
# `````````````````````````````````````````````````````````````````````
host_groups:
  Cisco_NX:
    - 'model:^N[23579][Kk].*$'
  rancid_exclude:
    - 'type:netdisco'
    - 'model:^VG[0-9]+$'
    - 'model:^IseVmK9$'
    - 'vendor:hp'
    - 'vendor:HPE'
    - 'vendor:^enterprises\..*'
    - 'vendor:vertiv'
    - 'vendor:lantronix'
  ansible_exclude:
    - 'model:^VG[0-9]+$'
    - 'vendor:hp'
    - 'vendor:aruba'
    - 'vendor:^enterprises\..*'
    - 'vendor:f5'
    - 'vendor:fortinet'
    - 'vendor:HPE'
    - 'vendor:lantronix'
    - 'vendor:vertiv'
  dc_mgmt:
    - 'op:and'
    - 'name:^xxxxxx$'
    - '10.x.y.z/24'

# Discover limit
#
discover_only:
  - '10.0.0.0/8'
  - '100.64.0.0/10'
  - '192.168.0.0/16'
discover_no:
  - 'name: xxxxxx$'

# vim: tabstop=2 expandtab

```
