### ISSUE TITLE
Strange listing of `discover` job in poller performance

### ISSUE THREAD

**Issue by earendilfr** [netdisco/netdisco#1079]
## Expected Behavior
In the poller performance page, when I see the performance of the different actions, I should see one line for `macsuck`, `arpnip`, `discover` or other poller type

## Current Behavior
But, for an unknown reason, I see the Discover part splited in multiple lines...
![image](https://github.com/netdisco/netdisco/assets/2353530/4c8e0a95-fb82-4c3e-8fb8-0f8826da27f5)

## Steps to Reproduce (for bugs)
1. Let the poller run few days
2. Check the poller performance page

## Context
It's worrying when we try to estimate the time of the discover job 

## Your Environment
* Netdisco version used: 2.63.1
* SNMP::Info version used: 3.92

## Config info (deployment.yml)
```yaml
#
# NETDISCO 2 CONFIGURATION FILE
#
# Settings in this file override share/config.yml
# See App::Netdisco::Manual::Configuration for more info.

# ------------------
# ESSENTIAL SETTINGS
# ------------------

database:
  name: 'netdiscodb'
  user: 'netdisco'
  pass: 'netdisco'

# -----------------
# LOG SETTINGS
# -----------------
log: 'warning'
log_format: '[%T] {PID: %P} {Level:%L} %m'

# set to false if you MUST maintain backwards compatibility
# with Netdisco 1.x web frontend.
# `````````````````````````````````````````````````````````
safe_password_store: true

# SNMP community string(s)
# ````````````````````````
device_auth:
  - tag: 'snmp-user-ro'
    user: 'snmp-user-ro'
    auth:
      proto: 'SHA'
      pass: 'xxx'
    priv:
      proto: 'AES'
      pass: 'xxx'
  - tag: 'sshbigip'
    driver: cli
    platform: BigIP
    only:
      - 10.208.233.98
      - 10.208.233.99
      - 10.208.236.6
      - 10.208.236.7
    username: netbackup
    ssh_master_opts:
      - "-i"
      - "~/.ssh/rancid_ed25519"


# this is the schedule for automatically keeping netdisco up-to-date
# ``````````````````````````````````````````````````````````````````
schedule:
  discoverall:
    when: '* */6 * * *'
  macwalk:
    when:
      min: '0,30'
  arpwalk:
    when:
      min: '15,45'
  nbtwalk: null
  expire:
    when: '20 23 * * *'
  makerancidconf:
    when: '30 */6 * * *'
  makeansiblehost:
    when: '30 */6 * * *'

# do not discover IP Phones or Wireless Access Points.
# usually these are visible as device neighbors but don't support
# SNMP, which just clogs up the job queue.
# ```````````````````````````````````````````````````````````````
#discover_no_type:
#  - '(?i)phone'
#  - '(?i)cisco\s+AIR-(L|C)AP'
discover_waps: false
discover_phones: false

# number of SNMP workers to run in parallel (in netdisco-backend).
# the default is twice the number of CPU cores. increase this if
# your system has few cores and the schedule is taking too long.
# ```````````````````````````````````````````````````````````````
workers:
  tasks: 'AUTO * 4'
  timeout: 600
  sleep_time: 1
  min_runtime: 0
  max_deferrals: 10
  retry_after: '1 day'

# number of parallel DNS queries for node names
# `````````````````````````````````````````````
dns:
  max_outstanding: 50

# Domain suffix to remove
# `````````````````````````````````````````````
domain_suffix:
  - '.example.com'

# We disable completely the Netbios discover
# `````````````````````````````````````````````````````````````````````
nbtstat_no:
  - 'any'

# Global tuning for MAC suck to take in count users in VLAN
# WARNING: on Cisco switch, you should allow polling on SNMP context for each VLAN
# `````````````````````````````````````````````````````````````````````
macsuck_all_vlans: true

# We clear job that didn't have run after 2 days
# `````````````````````````````````````````````````````````````````````
expire_jobs: 2

# Turn this on to have Netdisco do a reverse lookup of the device sysName.0 field 
# to use as the management IP address for a device.
# `````````````````````````````````````````````````````````````````````
reverse_sysname: true

# Web tune parameters
# `````````````````````````````````````````````````````````````````````
table_pagesize: 50

# LDAP authentication
# `````````````````````````````````````````````````````````````````````
ldap:
  servers:
    - 'ad.example.com'
  user_string: '%USER%@ad.example.com'
  opts:
    debug: 0

# Discover limit
#
discover_only:
  - '10.0.0.0/8'
  - '100.64.0.0/10'
  - '192.168.0.0/16'
discover_no:
  - 'excluded.example.com'

# vim: tabstop=2 expandtab

```
