### ISSUE TITLE
Per Group Expire Settings

### ISSUE THREAD

**Issue by robertlynch3** [netdisco/netdisco#1164]
## Expected Behavior

I have a host group for devices in a certain subnet. Those devices change very often and I'd like for those devices to expire from the database 3 days after they were last discovered. Devices in my other groups are very static, but with maintenance windows
 these devices may be not discoverable for 3 days even though their data is still valid.

Ideally I can set 1 `host_group` and set the `expire_devices` to 3 days, the other devices outside of that hostgroup set to the default.
## Current Behavior

All devices adhere to the `expire_devices` global setting.

## Possible Solution

- Implementing an option inside the host group to apply to that group.
- Implementing a dictionary to the `expire_X` that takes the group name as a key and the expiration date as a value
```
expire_devices:
 - 'group:lab_devices': 3
 - all: 10
```

## Context

This allows for the database to be more efficient with a subset of the environment that is going to change. It allows for better data when troubleshooting issues. 

## Your Environment

* Netdisco version used: 2.72.1
* SNMP::Info version used: 3.95

## Config info (deployment.yml)

```
host_groups:
  lab_devices:
    - 10.15.0.0/24
    #ideally has an expiration of 3 days
  datacenter_devices:
    - 10.17.0.0/24
```

**Comment by ollyg** [comment]
thanks for the suggestion @robertlynch3 ! I've implemented this in 792670b5

**Comment by robertlynch3** [comment]
@ollyg How is this config supposed to look? I have the following but it doesn't seem to be expiring 
```yml
host_groups:
  flex_switches:
    - 10.160.0.0/16
expire_devices:
  - flex_switches: 5
```
