### ISSUE TITLE
Version 2.72.1 wont redraw map of entire network

### ISSUE THREAD

**Issue by angelK12** [netdisco/netdisco#1166]
**Netdisco latest version:** 2.72.1     :(

Wont redraw the entire network map.

Under Neighbors >> the Redraw Map Button wont give the option to redraw the entire network like in previous versions.
![redraw](https://github.com/netdisco/netdisco/assets/43408973/fc5780c4-0a65-4d0f-8a27-2b7a3be277af)

**Comment by inphobia** [comment]
can you add this to your config (or change 2500 to how many devices you have) do be aware this will have a performance impact

```
sidebar_defaults:
  device_netmap:
    too_many_devices:
      default: 2500
```

https://github.com/netdisco/netdisco/wiki/Configuration#sidebar_defaults
