### ISSUE TITLE
Problem with TACACS

### ISSUE THREAD

**Issue by ubzmrh** [netdisco/netdisco#1182]
Hello !
I’m trying a new way to connect to Netdisco: TACACS!
My server is a Red Hat Enterprise Linux release 8.9 (Ootpa)
I added my user tacacs to Netdisco (in addition to my user radius) 
I configured in environments/deployment.yml 
```
tacacs:
  server: 10.251.44.1
  secret: 'a very complicated word'
  port: 49
  timeout: 3

```
I restarted netdisco-backend AND netdisco-web
And ... nothing!?
I made an IP trace with tcpdump and no traces!

I tried a connection with telnet and I can connect to the tacacs server. 
I can see my try in the tacacs server log and with tcpdump.

What did I do wrong ?
