### ISSUE TITLE
'switchport trunk native vlan' is getting set whenever a VLAN on an access port is changed

### ISSUE THREAD

**Issue by NMCPaul** [netdisco/netdisco#1218]
## Expected Behavior
When changing a VLAN through either the web interface or CLI, only the `switchport access vlan` should be changed instead of both that and the `switchport trunk native vlan` being changed.

## Current Behavior
Whenever I change a VLAN, it will change the `switchport access vlan` as requested, but will also add a `switchport trunk native vlan` even though the port is set to `switchport mode access`.  This isn't desired behavior as it really just clogs up the config.

## Possible Solution
Check for trunk vs access port prior to changing the VLAN so it can be more accurately done.

## Steps to Reproduce (for bugs)
1. Set a VLAN on a WS-C2960X-48FPS-L running 15.2(7)E8 and ensure it's set to access mode.
2. Discover the device with NetDisco.
3. Using NetDisco, change the VLAN to anything else.
4. Observe via `sh run int [WHATEVER]` that you now have an additional `switchport trunk native vlan` line.

## Context
It's just useless information that's making our configs less readable.

## Your Environment
* Netdisco version used: 2.76.5
* SNMP::Info version used: 3.970.1
* I have observed this on all of the 2960X devices I manage across several IOS versions.

## Config info (deployment.yml)
(only including what's changed from the defaults and omitting the SNMP credential section, the LDAP section, and the `discover_*` sections)
```
workers:
  tasks: '20'
dns:
  max_outstanding: 50
  no: ['fe80::/10','169.254.0.0/16','10.80.0.0/16','10.81.0.0/16','10.82.0.0/16']
navbar_autocomplete: false
jobs_qdepth: 200
table_pagesize: 24
show_errors: true
portctl_uplinks: true
node_freshness: 60
schemes: 'https'
```
