### ISSUE TITLE
pty error for Net/OpenSSH.pm when trying to use SSHCollector helper for ArubaOS-CX arp

### ISSUE THREAD

**Issue by jrbinks** [netdisco/netdisco#1230]
I'd thought that https://github.com/netdisco/netdisco/discussions/869 would help me along while the outstanding issues pulling the arp table via SNMP are contemplated (which tickets I cannot now find).

But when I try that, I get:

```
[18165] 2024-07-03 21:11:08 debug -> Cannot open a pty at /home/netdisco/perl5/lib/perl5/Net/OpenSSH.pm line 985.
[18165] 2024-07-03 21:11:08 debug â¬
 (error) Cannot open a pty at /home/netdisco/perl5/lib/perl5/Net/OpenSSH.pm line 985.
```
and of course there is no useful outcome.

Config is along the lines of

```
  - tag: ssharuba
    driver: cli
    platform: Aruba
    only: 'group:arubaosx_model'
    username: xxx
    password: xxx
    ssh_master_opts:
      - "-T"
      - "-o"
      - "StrictHostKeyChecking=no"

```

I would also quibble that the module should be renamed to SSHCollector/Platform/ArubaOSCX.pm to match the SNMP/Info module name, since that is what it is intended for; as the last comment in that discussion notes it doesn't work for ArubaOS (wireless controllers) as the show arp output is formatted differently.

Software	Version
App::Netdisco	2.76.5
SNMP::Info	3.970.1
