### ISSUE TITLE
Multiple SNMP communities

### ISSUE THREAD

**Issue by lucdnb** [netdisco/netdisco#1233]
Hi!

I have a annoying problem here. I dont get Netdisco work with multiple SNMP communities.
As the documentation says to do, there is some modes:

device_auth:
   - community: public
   - community: publictwo
   - community: mycommunity

or:

device_auth:
   - community: ['one', 'two', 'three']  

Or any other example that I saw on internet...

When I save the deployment.yml file and try to discover a device, I have the message:

> error: config: snmpv2 community in device_auth must be single item, not list

I have a lot of devices on my network and lot of differents strings. I'm having to change the file each time of discover devices.

Do you know if multiple string are really supported by Netdisco?

Thank you guys for you help!

**Comment by rc9000** [comment]
You should use the first style like in the example from the Wiki:
https://github.com/netdisco/netdisco/wiki/Configuration#device_auth

```
device_auth:
  - community: public
  - community: publictwo
  - community: mycommunity
    write: true
  - community: mycommunity2
    read: false
    write: true
```

(ie. device_auth is a list of multiple dictionaries, with at least one key "community" but optionally more)

Watch out for YAML issues like tabs vs. spaces, inconsistent number of spaces (use 2 or 4 everywhere) etc. Paste the config in a code block if it still doesn't work for you.

**Comment by usenkov999** [comment]
> You should use the first style like in the example from the Wiki: https://github.com/netdisco/netdisco/wiki/Configuration#device_auth
> 
> ```
> device_auth:
>   - community: public
>   - community: publictwo
>   - community: mycommunity
>     write: true
>   - community: mycommunity2
>     read: false
>     write: true
> ```
> 
> (ie. device_auth is a list of multiple dictionaries, with at least one key "community" but optionally more)
> 
> Watch out for YAML issues like tabs vs. spaces, inconsistent number of spaces (use 2 or 4 everywhere) etc. Paste the config in a code block if it still doesn't work for you.

I have same problem with multiple snmp communities.
your solution is not working :(

I have this configuration:
![image](https://github.com/user-attachments/assets/ee2f7eb4-4917-4ddd-8255-f3301fa4258c)

**Comment by lucdnb** [comment]
> [rc9000](/rc9000)

Yeah you rock! Now my Netdisco is trying multiple snmp strings one by one. Maybe my error was a yaml rules.

My contribuition for friend @usenkov999, my "deployment.yml" is working as bellow:

```
device_auth:
  - community: community1
  - community: community2
  - community: community3
  - community: community4
  - community: community5
  - community: community6
    read: true
    write: false
```

@rc9000 , by the way, can I use sshcollector in the same statement "device_auth"? As configured bellow?
```
device_auth:
  - community: community1
  - community: community2
  - community: community3
  - community: community4
  - community: community5
  - community: community6
    read: true
    write: false

  - tag: 'NXOS CLI'
    driver: 'cli'
    platform: 'NXOS'
    #only: 'group:test_routers'
    username: 'username'
    password: 'pass'
    ssh_master_opts:
      - "-o"
      - "StrictHostKeyChecking=no"
```

**Comment by ollyg** [comment]
Hi @usenkov999 you cannot have two communities in one tag. Probably should be:

```
device_auth:
  - tag: foo
    community: publicone
  - tag: bar
    community: publictwo
```
or just
```
device_auth:
  - community: publicone
  - community: publictwo
```
(same thing)
