### ISSUE TITLE
Backend looses its workers and stops running jobs after a while

### ISSUE THREAD

**Issue by JeroenvIS** [netdisco/netdisco#1236]
## Expected Behavior

We expect jobs like "discoverall", "macwalk" and "arpwalk" to be run according to the configured schedules.

## Current Behavior

After starting the backend, jobs are being run fine for quite a while (at least several days). After some unknown time, jobs are not being run any more - we can see that the timestamps for last_discover, last_macsuck and last_arpnip are not updated for any device any more.

## Possible Solution

Not sure. We have been running for a long time (months? years?) with a cron job that just restarts the netdisco-backend every night, but that's not a real solution.

## Steps to Reproduce (for bugs)

We have not been able to actively reproduce. If we don't restart the backend on a daily basis, it will take somewhere between a couple of days to a month at maximum before the backend fails to run jobs.

When jobs aren't run any more, we don't see anything in the logs/backend.log pointing to something that went wrong.

It appears that the "nd2 master" process is dead and no worker processes are active any more, when the issues starts; a `ps -ef | grep netdisco` output looks like this:

```
netdisco@linux786:~/logs$ ps -ef | grep netdisco
netdisco 2362887       1  0 Jul04 ?        00:19:30 netdisco-backend
netdisco 2362888 2362887  0 Jul04 ?        00:23:14 [nd2: master] <defunct>

```
For comparison, the same output on our test server with nightly restarts of the backend looks like this:
```
netdisco 1152781       1  0 03:00 ?        00:02:40 netdisco-backend
netdisco 1152782 1152781  0 03:00 ?        00:00:21 nd2: master
netdisco 1152843 1152782  0 03:00 ?        00:00:00 nd2: #1 sched: idle
netdisco 1152844 1152782  0 03:00 ?        00:02:13 nd2: #2 mgr: idle
netdisco 1274291 1152782  0 10:38 ?        00:00:00 nd2: #5 poll: #45413336: arpnip x.y.28.8
netdisco 1274294 1152782  3 10:38 ?        00:00:24 nd2: #10 poll: #45413318: arpnip a.b.0.203
netdisco 1277134 1152782 26 10:50 ?        00:00:23 nd2: #3 poll: #45413320: arpnip a.b.0.205
netdisco 1277241 1152782 25 10:50 ?        00:00:20 nd2: #6 poll: #45413319: arpnip a.b.0.204
netdisco 1277245 1152782 23 10:50 ?        00:00:15 nd2: #4 poll: #45413321: arpnip a.b.0.206
netdisco 1277287 1152782  0 10:51 ?        00:00:00 nd2: #9 poll: idle
netdisco 1277288 1152782  0 10:51 ?        00:00:00 nd2: #7 poll: idle
netdisco 1277296 1152782  1 10:51 ?        00:00:00 nd2: #8 poll: idle
```

## Context

We're using Netdisco to keep an accurate inventory. Lots of scripts in our network depend on Netdisco for an up-to-date inventory, eg for which devices to pull stats, backup configs, check and modify port settings, etc. Having stale data in Netdisco makes all the other scripts less reliable.

## Your Environment

* Netdisco version used: 2.070001
* SNMP::Info version used: 3.95

## Config info (deployment.yml)

Most relevant parts:
```
# daemon will keep netdisco up to date on this schedule
# `````````````````````````````````````````````````````
schedule:
  discoverall:
    when: '5 * * * *'
  macwalk:
    when:
      min: 20
  arpwalk:
    when:
      min: 50
  nbtwalk:
    when: '0 8,13,21 * * *'
  expire:
    when: '20 23 * * *'

# number of SNMP pollers to run in parallel (in netdisco-daemon)
# ``````````````````````````````````````````````````````````````
workers:
  pollers: 20

# amount parallel DNS resolution for node names
# `````````````````````````````````````````````
dns:
  max_outstanding: 50
```

## Device information
Not related to any specific device
