### ISSUE TITLE
Issue with device_identity renumber

### ISSUE THREAD

**Issue by earendilfr** [netdisco/netdisco#1257]
## Expected Behavior

I have done a `device_identity` configuration on my netdisco to use the correct IP address to pool my wan routers:
```yaml
device_identity:
  - 'group:filter_dev_dmvpn_router':
    - '10.12.32.0/24'
host_groups:
  filter_dev_dmvpn_router:
    - 'op:and'
    - 'vendor:cisco'
    - 'model:^(ASR.*|C11[0-9]+.*|ISR.*|C8500.*)$'
    - '100.64.0.0/10'
```

But, when netdisco discover a router with his wrong IP address (the EIGRP peer IP address), I don't want to perform the discover with the right one...
It seems there is an issue to update the IP address use to identity the device...

## Current Behavior
The output of the command of discover:
```
[409048] 2024-10-04 09:54:01  info App::Netdisco version 2.079001 loaded.
[409048] 2024-10-04 09:54:01  info discover: [10.12.32.111] started at Fri Oct  4 11:54:01 2024
[409048] 2024-10-04 09:54:37  info discover: finished at Fri Oct  4 11:54:37 2024
[409048] 2024-10-04 09:54:37  info discover: status error: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  duplicate key value violates unique constraint "device_module_pkey"
DETAIL:  Key (ip, index)=(10.12.32.111, 1249) already exists. [for Statement "UPDATE device_module SET ip = ? WHERE ( ip = ? )" with ParamValues: 1='10.12.32.111', 2='100.64.96.87'] at /opt/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/Device.pm line 352
```

## Your Environment

* Netdisco version used: 2.79.1
* SNMP::Info version used: 3.972.0

**Comment by ollyg** [comment]
Hi @earendilfr 
I'm a bit confused when you say "when netdisco discovers a router with the wrong IP address  ... I don't want to perform the discover with the right one."

The target of device identity is the IP address used for discovery.

If you just wish to use the DNS alias of one interface for the device name, so they are called similar thing, but use another interface for discovery, I don't think that's possible in Netdisco today.

Please let me know if I've misunderstood this!

oliver.

**Comment by earendilfr** [comment]
I will try to be more understandable:
- I have a router connected through my VPN to my hub router.
- the router has at least two interface:
  - a loopback interface used to manage the device (IP: `10.12.32.103` resolved as DNS rtr-site-01.example.com)
  - a Tunnel interface used for the VPN with my hub router (IP: `100.64.96.78` resolved as DNS rtr-site-01-internet.example.com)
- there is a dynamique routing protocole between the hub router and the spoke router (EIGRP)

netdisco discover the new site router through the IP 100.64.96.78 but I want to found a solution to say to netdisco to use the loopback IP address to discover and pool this device.

Currently, my configuration is (I have only keeped the part that seems to be important in this case:
```yaml
# Domain suffix to remove
# `````````````````````````````````````````````
domain_suffix:
  - '.net.fhvi.ch'
  - '.adi.adies.lan'
  - '.voip.fhvi.ch'

# Configure the interface used for device identity
# ````````````````````````````````````````````````
device_identity:
  - 'group:filter_dev_dmvpn_router':
    - '10.12.32.0/24'

# We disable completely the Netbios discover
# `````````````````````````````````````````````````````````````````````
nbtstat_no:
  - 'any'

# Global tuning for MAC suck to take in count users in VLAN
# WARNING: on Cisco switch, you should allow polling on SNMP context for each VLAN
# `````````````````````````````````````````````````````````````````````
macsuck_all_vlans: true

# We clear job that didn't have run after 2 days
# `````````````````````````````````````````````````````````````````````
expire_jobs: 2

# We clear devices that doesn't have been polled after 14 days
# `````````````````````````````````````````````````````````````````````
expire_devices:
  'group:__ANY__': 14

# Turn this on to have Netdisco do a reverse lookup of the device sysName.0 field 
# to use as the management IP address for a device.
# `````````````````````````````````````````````````````````````````````
reverse_sysname: true

# Custom groups / ACL
# `````````````````````````````````````````````````````````````````````
host_groups:
  filter_dev_dmvpn_router:
    - 'op:and'
    - 'vendor:cisco'
    - 'model:^(ASR.*|C11[0-9]+.*|ISR.*|C8500.*)$'
    - '100.64.0.0/10'
  filter_cisco_no_snmp_mac:
    - 'op:and'
    - 'vendor:cisco'
    - 'model:^C1111.*$'
  filter_dev_net_ip:
    - '10.0.0.0/8'
    - '100.64.0.0/10'
    - '172.16.0.0/12'
    - '192.168.0.0/16'
  filter_dev_net_regex:
    - !!perl/regexp ^.*\.example\.com$
    - '100.64.96.0/24'
    - '100.64.128.0/24'
  filter_dev_net_devices:
    - 'op:and'
    - 'group:filter_dev_net_ip'
    - 'group:filter_dev_net_regex'
    - '!10.208.233.244'
    - '!10.208.233.245'
    - '!10.208.233.246'

# Discover limit
#
devices_only:
  - 'group:filter_dev_net_devices'

# vim: tabstop=2 expandtab
```

My question is: did my configuration is OK to say to netdisco, when I try to reach a device through an IP in network 100.64.0.0/10 to try to rediscover with an IP 10.12.32.x already present in the router?
