### ISSUE TITLE
netdisco-deploy OUI data update fails with psql: error:  when specifying port for database host

### ISSUE THREAD

**Issue by bitbin** [netdisco/netdisco#1281]
Netdisco 2.081003

Have database host defined with a non-default port in ~/environments/deployment.yml
```
database:
  name: 'netdisco_a'
  user: 'netdisco_a'
  pass: 'MyPassword'
  host: 'localhost;port=5433'
```

run ~/bin/netdisco-deploy - all is fine until the OUI data update
```
Download and update vendor MAC prefixes (OUI data)? [y/N]: y
Updating OUI, Manufacturers, Enterprises, and Products... psql: error: could not translate host name "localhost;port=5433" to address: Name or service not known
done.
```

Not sure if this is the proper fix, but I was able to get it working with an update to ‎lib/App/Netdisco/Configuration.pm - diff attached

Thank you for all your work on Netdisco!

[Configuration.pm.diff.txt](https://github.com/user-attachments/files/18446203/Configuration.pm.diff.txt)
