### ISSUE TITLE
Discover failed: Could not snmp connect to <IP> || MIB/OUI Download/Update failed

### ISSUE THREAD

**Issue by Fadelhi** [netdisco/netdisco#307]
hey, 
i tried to install netdisco on ubuntu lts 16.04 with this guide.

https://metacpan.org/pod/App::Netdisco

but i got 2 problems:
by executing this command 

`~/bin/netdisco-deploy`

the download and update of the OUI and MIB always fails

then i tried to download them on the "offline" way and execute them with 

```
su - postgres
wget -O oui.txt http://standards-oui.ieee.org/oui/oui.txt
~/bin/netdisco-deploy ./oui.txt
```

but i receive this error

> utf8 "\xE9" does not map to Unicode at /usr/lib/x86_64-linux-gnu/perl/5.22/Encode.pm line 200.

    

> 191 if ( ref($enc) eq 'Encode::Unicode' ) {
>     192         my $warn = '';
>     193         {
>     194             local $SIG{__WARN__} = sub { $warn = shift };
>     195             $string = $enc->decode( $octets, $check );
>     196         }
>     197         warnings::warnif('utf8', $warn) if length $warn;
>     198     }
>     199     else {
>     200         $string = $enc->decode( $octets, $check );
>     201     }
>     202     $_[1] = $octets if $check and !ref $check and !( $check & LEAVE_SRC() );
>     203     return $string;

the second problem is on the web interface, after discovering an IP i get this Error

> Discover failed: Could not snmp connect to <IP>

i hope someone can help me ^^ :)

**Comment by ollyg** [comment]
Hi Fadelhi, thanks for reporting this. The UTF8 issue has been reported by another user as well. I will investigate and let you know.

Usually if Netdisco cannot connect to the device, the SNMP config in deployment.yml is not correct or has the wrong formatting. Please can you send me your SNMP config (change the passwords/secrets)?

You can also test on the command line using `~netdisco/bin/netdisco-do discover -D -d 1.2.3.4`

regards,
oliver.

**Comment by Fadelhi** [comment]
hey ollyg :D
my deployment conf

```
#
# NETDISCO 2 CONFIGURATION FILE
#
# Settings in this file override share/config.yml
# See App::Netdisco::Manual::Configuration for more info.

# ------------------
# ESSENTIAL SETTINGS
# ------------------

database:
  name: 'netdisco'
  user: '*********'
  pass: '*********'
  #host: 'localhost'

# --------------------
# RECOMMENDED SETTINGS
# --------------------

# set to false if you MUST maintain backwards compatibility
# with Netdisco 1.x web frontend.
# `````````````````````````````````````````````````````````
safe_password_store: true

# will be stripped from fqdn when displayed in the web UI
# also, do not forget the leading dot.
# ```````````````````````````````````````````````````````
domain_suffix: '************'

# SNMP community string(s)
# ````````````````````````
snmp_auth:
  - tag: 'default_v2_readonly'
    community: '*********'
    read: true
    write: false
  - tag: 'default_v2_for_write'
    community: 'private'
    read: false
    write: true

# this is the schedule for automatically keeping netdisco up-to-date
# ``````````````````````````````````````````````````````````````````
schedule:
  discoverall:
    when: '5 7 * * *'
  macwalk:
    when:
      min: 20
  arpwalk:
    when:
      min: 50
  nbtwalk:
    when: '0 8,13,21 * * *'
  expire:
    when: '20 23 * * *'

# do not discover IP Phones or Wireless Access Points.
# usually these are visible as device neighbors but don't support
# SNMP, which just clogs up the job queue.
# ```````````````````````````````````````````````````````````````
discover_no_type:
  - '(?i)phone'
  - '(?i)(?:wap|wireless)'

# number of SNMP workers to run in parallel (in netdisco-daemon).
# the default is twice the number of CPU cores. increase this if
# your system has few cores and the schedule is taking too long.
# ```````````````````````````````````````````````````````````````
workers:
  tasks: 'AUTO * 2'
# number of parallel DNS queries for node names
# `````````````````````````````````````````````
dns:
  max_outstanding: 50

# set to true to globally disable authentication/login.
# create a user called "guest" if you want to assign port/admin rights.
# `````````````````````````````````````````````````````````````````````
no_auth: false
```

I fixed the first problem.... but now there is another one :| xD

if i execute this command 

`/home/netdisco/bin/netdisco-deploy ./oui.txt`

i receive this error 

```
Would you like to deploy the database schema? [y/N]: y
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 95
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','netdisco',...) failed: FATAL:  Peer authentication failed for user "netdisco" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1517. at /home/netdisco/perl5/bin/netdisco-db-deploy line 106 at /home/netdisco/perl5/bin/netdisco-db-deploy line 106
DB schema update complete.
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 95
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco','netdisco',...) failed: FATAL:  Peer authentication failed for user "netdisco" at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1517. at /home/netdisco/bin/netdisco-deploy line 162
```
