### ISSUE TITLE
netdisco-sshcollector public key auth doesn't work

### ISSUE THREAD

**Issue by rc9000** [netdisco/netdisco#473]
## Expected Behavior

The documentation says using "-" as password should enable public key auth. 

## Current Behavior

It doesn't, and there is no way to pass the key and passphrase to be used.

## Possible Solution

Either properly implement the feature or remove it from the documentation.

## Your Environment

* Netdisco version used: https://github.com/netdisco/netdisco/releases/tag/2.040000

**Comment by inphobia** [comment]
it does actually work if you define it like:

```
sshcollector:
  - hostname: 'd8-n9k1.somewhere.com'
    user: "myuser"
    password:
    platform: "NXOS"
```

and have a working public key for the netdisco user that matches the remote user defined under sshcollector.

this is however with pubkeys that don't use a passphrase.
