### ISSUE TITLE
Losing "Free Port" information after Switch Restart

### ISSUE THREAD

**Issue by cRAYonhere** [netdisco/netdisco#613]
## Expected Behavior

After switch reboot, we would like to have the ability to see when was the last time a node was seen on the port.
## Current Behavior

If the switch reboots, the "Free Port" information is lost. 
## Steps to Reproduce (for bugs)

1. 

## Context

Due to switch upgrades and power failures switches are rebooted and all the data pertaining to "Free Port" is lost. This creates problems later when we try to weed out un-used ports.

## Your Environment

* Netdisco version used: 
* SNMP::Info version used:

**Comment by inphobia** [comment]
i'm not quite sure what to make of this, for me this works just fine. here's an access point i used as an example:

![image](https://user-images.githubusercontent.com/39005454/62575319-c9b3f800-b89a-11e9-9d50-4d9f3a79e874.png)


![image](https://user-images.githubusercontent.com/39005454/62575252-a6894880-b89a-11e9-90a1-413f336d5c75.png)

as you can see both archived clients (the one with the book icon in front of them) as active clients are shown; reboots didn't make a difference.

relevant config i'm using:
```
nbtstat_no: "any"
node_freshness: 1500
expire_jobs: 5
#expire_nodes: 3
expire_nodes_archive: 75
devport_vlan_limit: 250

schedule:
  discoverall:
    when: '5 3,7,11,15,19,23 * * *'
  macwalk:
    when:
      min: 55
      hour: '*/4'
  arpwalk:
    when:
      min: 5
      hour: '*/4'
  nbtwalk: null
  expire:
    when: '30 23 * * *'
```
