### ISSUE TITLE
SNMP not working

### ISSUE THREAD

**Issue by StewAlexanderACC** [netdisco/netdisco#623]
SNMP isn't working on the NetDisco container

![image](https://user-images.githubusercontent.com/48565067/61459019-d9928900-a939-11e9-9651-4d87bbe4dc43.png)

```
support@netdisco-new ~/n/config> cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
support@netdisco-new ~/n/config>
```

**Comment by StewAlexanderACC** [comment]
```
# --------------------
# RECOMMENDED SETTINGS
# --------------------

# SNMP community string(s)
# ````````````````````````
device_auth:
  - tag: 'default_v2_readonly'
    community: 'blah'
    read: true
    write: false
#  - tag: 'default_v2_for_write'
#    community: 'private'
#    read: false
#    write: true
```
Where "blah" is our community string
