### ISSUE TITLE
configuration for device_auth action key not working

### ISSUE THREAD

**Issue by antonc42** [netdisco/netdisco#694]
## Expected Behavior
Configure common SNMP community for all devices.
Configure a different SNMP community for arpnip action on a particular device.
Discover device, then perform arpnip.
Discover uses common community string.
Arpnip **uses different community string**

## Current Behavior
Configure common SNMP community for all devices.
Configure a different SNMP community for arpnip action on a particular device.
Discover device, then perform arpnip.
Discover uses common community string.
Arpnip **also uses common community string**

## Steps to Reproduce
1.  Configure SNMP community strings.  
    ```
    device_auth:
      - tag: 'vrf'
        community: 'public::1'
        read: true
        write: false
        action: arpnip
        only:
          - 10.1.1.1
      - tag: 'readonly'
        community: 'public'
        read: true
        write: false
    ```
2.  Discover via `netdisco-do`. Observe the common community string being used.  
    ```
    SHOW_COMMUNITY=1 netdisco-do discover -d 10.1.1.1 -DIQ
    ```
2.  Arpnip via `netdisco-do`. Observe the common community string being used.  
    ```
    SHOW_COMMUNITY=1 netdisco-do arpnip -d 10.1.1.1 -DIQ
    ```

## Context
We have recently started using Extreme (formerly Avaya) VSP 8400, 7200, and 7400 network switches. We have also just started to use different VRFs to segment our network. Querying for ARP via SNMP with the base community string only will show ARP for the default VRF. We asked Extreme support how to query the ARP for a different VRF and were told to use the base community string with `::vrfid` appended (where ``vrfid`` is a number representing the VRF we wanted to query). We successfully performed manual SNMP queries using this constructed community string and were able to get the ARP table for a non-default VRF.
When we configure Netdisco in the way described to get the ARP from a non-default VRF, it still uses the common community string, resulting in the wrong ARP table being returned. When we try to use the constructed community string as the only one for the device (i.e. without the `action: arpnip` key) device discovery fails.

## Your Environment
* Netdisco version used: 2.044004
* SNMP::Info version used: 3.70
* Centos 7

## Config info (deployment.yml)
[deployment.yml.txt](https://github.com/netdisco/netdisco/files/4079291/deployment.yml.txt)

## Device information
[netdisco_device.txt](https://github.com/netdisco/netdisco/files/4079251/netdisco_device.txt)
