### ISSUE TITLE
IPv6 only Switches can not be discovered with default config

### ISSUE THREAD

**Issue by kampa133** [netdisco/netdisco#699]
Error:
info discover: status defer: deferred job with no device creds

Workaround; adding IPv6 address or networks to the device_auth section.

```
device_auth:
  - tag: default_v2_readonly
    community: public
    read: true
    write: false
  - tag: ipv6_test
    community: public
    read: true
    write: false
    only:
      - 2001:db8::/32
```
