### ISSUE TITLE
Continuous groing size of the postgrsql database

### ISSUE THREAD

**Issue by earendilfr** [netdisco/netdisco#802]
## Expected Behavior
Since few weeks, I can see my netdisco database that perform a continuous growing.
In 4 days, the database size increasing from 4GB.

## Possible Solution
I suspect that something doesn't perform a correct clean-up in postgresql database.
I have "solved" the issue with running a VACUUM FULL on table in the database.

## Context
Netdisco environment: 
Statistics for this installation
427 devices with 2,076 IPs
29,721 interfaces of which 13,008 are up
707 layer 2 links between devices
65,119 nodes logged, of which 20,503 are active
31,998 IPs logged, of which 16,888 are active
Statistics last generated on 2021-08-15

## Your Environment
App::Netdisco 	2.47.8
SNMP::Info 	3.73
DB Schema 	65
PostgreSQL 	12.00.2
Perl 	5.16.3

## Config info (deployment.yml)
```
#
# NETDISCO 2 CONFIGURATION FILE
#
# Settings in this file override share/config.yml
# See App::Netdisco::Manual::Configuration for more info.

# ------------------
# ESSENTIAL SETTINGS
# ------------------

database:
  name: 'netdiscodb'
  user: 'netdisco'
  pass: 'xxx'
  #host: 'localhost'

# -----------------
# LOG SETTINGS
# -----------------
log: 'warning'
log_format: '[%T] {PID: %P} {Level:%L} %m'

# -----------------
# CLEAN-UP RULES
# -----------------
#node_freshness: 1440
#expire_devices: 30
#expire_nodes: 90
#expire_nodes_archive: 90

# this is the schedule for automatically keeping netdisco up-to-date
# ``````````````````````````````````````````````````````````````````
schedule:
  discoverall:
    when: '5 */3 * * *'
  macwalk:
    when:
      min: '*/20'
  arpwalk:
    when:
      min: '15,45'
  nbtwalk: null
  expire:
    when: '20 23 * * *'
  makerancidconf:
    when: '0 */3 * * *'
```
