### ISSUE TITLE
Column order wrong when displaying custom fields

### ISSUE THREAD

**Issue by rc9000** [netdisco/netdisco#948]
I've added

```
custom_fields:
  device_port:
    - name: 'networkarea'
      label: 'Network Area'
      editable: true
```

Now if I go to ports and enable just the status column, everything is fine:

![s1](https://user-images.githubusercontent.com/1247031/207294394-71565846-3059-425b-9480-00a84ecba478.png)

But as soon as I show also the 'Network Area' column, the columns are swapped:

![scr 2022-12-13 at 11 38 02](https://user-images.githubusercontent.com/1247031/207295567-73704abd-5eaf-4fc8-bcbb-1eacff21fc1a.png)

(also the fields in the status column now have the pen-icon to edit it when hovering)

I think I've also seen this before sometimes with other columns, but I was not able to reproduce it easily. Maybe it's somehow related to the column ordering in the config.yml.
