### ISSUE TITLE
match Cisco ASA devices if they have an IP in prefix

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#987]
From Brian Kelly on mail list

I’m looking for something to match Cisco ASA devices if they have an IP in the `172.31.0.0/16` space on their management interface and if so use the management IP for the device’s ID.

````
host_groups:
  cisco_asa:
    - 'op:and'
    - 'vendor:cisco'
    - 'model:.*(?i:ASA).*'
  device_with_management_ip:
    - 'op:and'
    - 'port:(?i)management'
    - '172.31.0.0/16'
  asa_with_management_ip:
    - 'op:and'
    - 'group:cisco_asa'
    - 'group:device_with_management_ip'

device_identity:
  'group:asa_with_management_ip':
    - 'port:(?i)management'
````
