### ISSUE TITLE
report - recent added devices

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#991]
courtesy @alcatron

```
reports: 
  - tag: recent
    category: Device
    label: 'Recent Devices Added Past 2 months'
    columns:
      - {ip: 'Device IP'}
      - {name: 'Device Name'}
      - {creation: 'Date Added'}
      - {location: 'Location'}
      - {contact: 'Contact'}
      - {serial: 'Serial'}
      - {model: 'Model'}
      - {vendor: 'Vendor'}
      - {os: 'Operating System'}
      - {os_ver: 'OS Version'}
    query: |
      SELECT ip AS ip, name AS name, creation AS creation, location AS location, contact AS contact, serial AS serial, model AS model, vendor AS vendor, os AS os, os_ver AS os_ver
      FROM device
      WHERE creation > now() - interval '8 weeks'
      ORDER BY creation DESC   
```
